### PR TITLE
Use go modules with go1.11

### PR DESCRIPTION
**Pull request by mohammedfakhar**
I tried to update Go version to 1.11, but even though it compiles fine on Mac (without using any flags, using `go build .`)

when I run `docker build .` it fails with:
```
loadinternal: cannot find runtime/cgo
```
then I tried few things and found that `-linkmode external` (with Go 1.11) seems to be the problem (even on Mac); couldn't find a fix yet. If someone knows, please let me know. Thanks

### CODE REVIEW

**Comment by ahmetb** [comment]
This PR doesn't use the `vendor/` directory and downloads things from scratch.

image

We might need to set `GOFLAGS=-mod=vendor` to enforce use of vendor but that will prevent go-get'ing gox.

The best solution here could be just removing `vendor/` for good.

**Comment by mohammedfakhar** [comment]
thanks! let me try.

**Comment by ahmetb** [comment]
I just revisited this by `rm -rf vendor/ Gopkg*` and initialized module cleanly. I nicely got a file like:

```
module github.com/grpc-ecosystem/grpc-health-probe

require google.golang.org/grpc v1.17.0
```

and builds seem to be working fine ✅ once I:
- changed release step (`gox`) to `env -u GOPATH gox` (which unsets GOPATH)
- deleted `dep` related steps

in travis.yml. Build: https://travis-ci.org/grpc-ecosystem/grpc-health-probe/builds/470400544

Would you like to make these changes yourself –or want me to push to your branch (it'll still get merged with your name)?

**Comment by mohammedfakhar** [comment]
@ahmetb I am so sorry, I moved to Android team and didn't have time look at it again, now I still don't have Go setup on this machine, I will be thankful if you can push to this branch.

thank you!

**Comment by mohammedfakhar** [comment]
Thank you so much!

**Pull request merged**
