### PR TITLE
build p8le package

### PR DESCRIPTION
**Pull request by dreamryx**
Commit for building p8le package.

### CODE REVIEW

**Comment by ahmetb** [comment]
LGTM
1. please sign the CLA
2. out of curiosity, do you have a legitimate use case for this? I'd be interest in hearing.

**Comment by dreamryx** [comment]
I signed it!

**Comment by dreamryx** [comment]
I signed it!

**Comment by dreamryx** [comment]
@ahmetb  Thanks for your review!   I need p8le verison to build docker image for katib-manager.   The link is [dockerfile](https://github.com/kubeflow/katib/blob/master/cmd/manager/Dockerfile).

**Comment by ahmetb** [comment]
@dreamryx Do you mind signing the CLA?

**Comment by dreamryx** [comment]
@ahmetb I'm trying to signed it.  But I don't know why I could not pass it.  I'm trying to figure it out.  :(

**Comment by dreamryx** [comment]
I signed it!

**Comment by dreamryx** [comment]
signed CLA.

**Comment by dreamryx** [comment]
I signed it!

**Comment by ahmetb** [comment]
@dreamryx I think you haven't signed it properly with your email address on the commit. I'll close this and fix myself.

**Comment by dreamryx** [comment]
@ahmetb OK.  I shall use another email address to commit code to have a try.

**Comment by ahmetb** [comment]
I already made a release with this change.

**Comment by dreamryx** [comment]
@ahmetb Thanks!

**Pull request closed without merging**
