### PR TITLE
updating golang.org/x/text version

### PR DESCRIPTION
**Pull request by BarsemianGeorgik**
Hello there,

golang.org/x/text v0.3.2  version library represents serious security threats,
it is well documented at https://groups.google.com/forum/#!topic/golang-announce/bXVeAmGOqz0
A safe fix version is v0.3.3

Best Regards!

### CODE REVIEW

**Comment by BarsemianGeorgik** [comment]
@googlebot I signed it!

**Comment by ahmetb** [comment]
Thanks. I don't think this warrants a new release because this tool is meant to be used to connect to the servers in the same host i.e. the loopback interface, where it's not susceptible to external attacks.

**Comment by ahmetb** [comment]
Also aren’t you supposed to update go.sum as well?

**Comment by BarsemianGeorgik** [comment]
Thank you for the consideration! I will be closing the PR to continue the work

**Comment by BarsemianGeorgik** [comment]
I will open a second PR to validate the Google email check

**Pull request closed without merging**
